---
name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - .github/workflows/ci.yml

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: test dotfiles
        timeout-minutes: 40
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          provenance: false
          build-args: |
            base_image=ubuntu
            code_name=latest
          secrets: |
            "DOTFILES_REPO=${{ secrets.DOTFILES_REPO }}"
