---
name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - .github/workflows/ci.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GHCR
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: test dotfiles
        timeout-minutes: 40
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          provenance: false
          build-args: |
            BASE_IMAGE=ubuntu
            CODE_NAME=noble
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:noble-cache
          secrets: |
            "DOTFILES_REPO=${{ secrets.DOTFILES_REPO }}"
