---
name: cleanup

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/clean-up.yml
  schedule:
    - cron: 30 23 * * 1

permissions: write-all

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/snok/container-retention-policy/issues/63
      # - name: Delete untagged
      #   uses: Chizkiyahu/delete-untagged-ghcr-action@main
      #   with:
      #     token: ${{ github.token }}
      #     repository: ${{ github.repository }}
      #     repository_owner: ${{ github.repository_owner }}
      #     package_name: dotfiles
      #     untagged_only: true
      #     owner_type: user

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 1

      - name: Delete runs by state
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_by_state_pattern: deleted

      - name: Delete runs by conclusion
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: action_required, cancelled, failure, skipped
