---
name: cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1,4

permissions: write-all

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: old
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 3
          keep_minimum_runs: 0

      - name: deleted
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: deleted

      - name: cancelled
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: cancelled

      - name: failure
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: failure

      - name: skipped
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: skipped
