---
name: Manual
run-name: build-${{ inputs.code_name }}-${{ inputs.uid }}:${{ inputs.gid }}

on:
  workflow_dispatch:
    inputs:
      code_name:
        required: true
        description: os code name
        type: string
        default: noble
      uid:
        required: true
        description: user id
        type: number
        default: 1000
      gid:
        required: true
        description: group id
        type: number
        default: 1000

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GHCR
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        uses: docker/build-push-action@master
        with:
          context: .
          file: manual.Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          build-args: |
            IMAGE_NAME=ghcr.io/${{ github.repository }}
            CODE_NAME=${{ inputs.code_name }}
            USER_ID=${{ inputs.uid }}
            GROUP_ID=${{ inputs.gid }}
          secrets: |
            "DOTFILES_REPO=${{ secrets.DOTFILES_REPO }}"
          tags: |
            ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/${{ secrets.ACR_IMAGE_NAME }}:${{ inputs.code_name }}-${{ inputs.uid }}-${{ inputs.gid }}
